#!/bin/bash

##
## config file
FILE=/etc/hyperion/vm.args
echo "==> config ${FILE}"


##
## set HOST address
test -z "${HOST}" && HOST=$(ip addr show eth1 | sed -n 's/.*inet \([0-9]*.[0-9]*.[0-9]*.[0-9]*\).*/\1/p')
sed -i -e "s/@\(127.0.0.1\)/@${HOST}/g" ${FILE}

case $1 in
   console)
      ${REL}/bin/hyperion console
      ;;

   *)
      ${REL}/bin/hyperion $1

      while true ;
      do
         sleep 3600
      done
      ;;
esac
