#!/bin/bash

##
## config file
FILE=${REL}/releases/${VSN}/vm.args
echo "==> config ${FILE}"


##
## set HOST address
if [ -z "${HOST}" ] ;
then
HOST=$(ip addr show eth0 | sed -n 's/.*inet \([0-9]*.[0-9]*.[0-9]*.[0-9]*\).*/\1/p')
fi
sed -i -e "s/@\(127.0.0.1\)/@${HOST}/g" ${FILE}


${ROOT}/bin/hyperion console

while true ;
do
   sleep 3600
done
